### ISSUE TITLE
你好,怎么加入这个每天python的学习计划?

### ISSUE THREAD

**Issue by wujunze** [AplusB/PythonEveryday#1]
你好,怎么加入这个每天python的学习计划?

**Comment by ybai62868** [comment]
等元旦以后，开始，现在已经暂停两个月了，，最近太忙了，望理解。。。

2016-11-22 10:06 GMT+08:00 吴钧泽 notifications@github.com:

**Comment by wujunze** [comment]
好的  3Q

**Comment by wujunze** [comment]
好的  3Q
